--
-- PostgreSQL database dump
--

\restrict tcsxKuOTL1ExnYlBGTKGNuphnhUL2pHyjG66OJWPDTf4VNb2IrmCFzOcrgY2crz

-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: category; Type: TABLE; Schema: public; Owner: madhav-jariwala
--

CREATE TABLE public.category (
    id integer NOT NULL,
    categoryname character varying(50) NOT NULL
);


ALTER TABLE public.category OWNER TO "madhav-jariwala";

--
-- Name: category_id_seq; Type: SEQUENCE; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE public.category ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cosmetic_item; Type: TABLE; Schema: public; Owner: madhav-jariwala
--

CREATE TABLE public.cosmetic_item (
    productid integer NOT NULL,
    productname character varying(50) NOT NULL,
    sellprice integer,
    stock integer,
    costprice integer,
    category_id integer,
    CONSTRAINT cosmetic_item_costprice_check CHECK (((costprice > 0) AND (costprice < 999999))),
    CONSTRAINT cosmetic_item_sellprice_check CHECK (((sellprice > 0) AND (sellprice < 999999))),
    CONSTRAINT cosmetic_item_stock_check CHECK (((stock > 0) AND (stock < 99999)))
);


ALTER TABLE public.cosmetic_item OWNER TO "madhav-jariwala";

--
-- Name: cosmetic_item_productid_seq; Type: SEQUENCE; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE public.cosmetic_item ALTER COLUMN productid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cosmetic_item_productid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: category; Type: TABLE DATA; Schema: public; Owner: madhav-jariwala
--

COPY public.category (id, categoryname) FROM stdin;
1	Makeup
2	Skin
4	Body
16	Bags
3	Hairs
\.


--
-- Data for Name: cosmetic_item; Type: TABLE DATA; Schema: public; Owner: madhav-jariwala
--

COPY public.cosmetic_item (productid, productname, sellprice, stock, costprice, category_id) FROM stdin;
1	Himalayan Facewash	160	5	120	4
2	Sunscreen	652	30	516	2
3	Foundation	950	30	600	1
5	Shampoo	561	51	350	3
\.


--
-- Name: category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: madhav-jariwala
--

SELECT pg_catalog.setval('public.category_id_seq', 16, true);


--
-- Name: cosmetic_item_productid_seq; Type: SEQUENCE SET; Schema: public; Owner: madhav-jariwala
--

SELECT pg_catalog.setval('public.cosmetic_item_productid_seq', 6, true);


--
-- Name: category category_pkey; Type: CONSTRAINT; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);


--
-- Name: cosmetic_item cosmetic_item_pkey; Type: CONSTRAINT; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE ONLY public.cosmetic_item
    ADD CONSTRAINT cosmetic_item_pkey PRIMARY KEY (productid);


--
-- Name: category uq_catergory; Type: CONSTRAINT; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE ONLY public.category
    ADD CONSTRAINT uq_catergory UNIQUE (categoryname);


--
-- Name: cosmetic_item fk_category; Type: FK CONSTRAINT; Schema: public; Owner: madhav-jariwala
--

ALTER TABLE ONLY public.cosmetic_item
    ADD CONSTRAINT fk_category FOREIGN KEY (category_id) REFERENCES public.category(id);


--
-- PostgreSQL database dump complete
--

\unrestrict tcsxKuOTL1ExnYlBGTKGNuphnhUL2pHyjG66OJWPDTf4VNb2IrmCFzOcrgY2crz

